apiVersion: v2
name: openg2p-registry-gen2
description: A Helm chart for OpenG2P Registry Gen2
type: application
version: 4.0.0-develop
dependencies:
- name: common
  repository: https://openg2p.github.io/openg2p-helm
  version: 2.30.0
- name: postgres-init
  version: 0.0.0-develop
  repository: https://openg2p.github.io/openg2p-helm
  condition: postgres-init.enabled
- name: redis
  version: 19.6.4
  repository: https://openg2p.github.io/openg2p-helm
  condition: redis.enabled
- name: openg2p-id-generator
  alias: idgenerator
  version: 0.0.0-develop
  repository: https://openg2p.github.io/openg2p-helm
  condition: idgenerator.enabled
- name: keycloak-init
  version: 0.0.0-develop
  repository: https://openg2p.github.io/openg2p-helm
  condition: keycloak-init.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
keywords:
  - openg2p-registry
  - registry
  - gen2
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P Registry Gen2"
  openg2p.org/add-to-rancher: ""
